/* 第3章：數量關係
   依六上教冊：3-1圖形和數形的規律、3-2和差積商不變、3-3間隔問題。
   範圍：由具體情境觀察、推理並以文字或算式表徵；不使用代數符號推導。 */
window.DECK=window.DECK||[];
(function(){
  const C='#059669',B='#2563eb',A='#d97706',R='#e11d48',M='#475569';
  const svg=(vb,s)=>`<div style="width:100%;text-align:center"><svg viewBox="${vb}" style="max-width:100%">${s}</svg></div>`;
  const t=(x,y,s,c='#172033',z=16,a='middle')=>`<text x="${x}" y="${y}" text-anchor="${a}" font-size="${z}" font-weight="700" fill="${c}">${s}</text>`;
  const b=(x,y,w,h,f,st='#cbd5e1')=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="12" fill="${f}" stroke="${st}" stroke-width="2"/>`;
  const eg=(q,steps,ans)=>({q,steps,ans});
  const cards=rows=>svg('0 0 440 220',rows.map((r,i)=>`${b(55,25+i*58,330,45,i%2?'#eff6ff':'#ecfdf5',i%2?B:C)}${t(220,54+i*58,r,i%2?B:C,17)}`).join(''));
  const slides=[
    {sec:'3-1',secName:'圖形和數形的規律',title:'重複排列要先找出一組，再看位置的餘數',points:['圈出最短而且會重複的一組。','總位置÷每組數量，餘數指出組內位置。','整除時要看每組的最後一個。'],formula:{label:'藍、白、紅、白重複',tex:'21\\div4=5\\cdots1'},visual:h=>{h.innerHTML='<div><div id="fig"></div><div class="ictrl"><label>第 <span class="ival" id="pv">5</span> 張</label><input id="ps" type="range" min="1" max="12" value="5"></div></div>';const cs=['#2563eb','#f8fafc','#ef4444','#f8fafc'],ns=['藍色','白色','紅色','白色'],draw=()=>{const n=+h.querySelector('#ps').value,p=(n-1)%4;h.querySelector('#pv').textContent=n;h.querySelector('#fig').innerHTML=svg('0 0 440 180',`${Array.from({length:8},(_,i)=>`${b(22+i*51,48,43,60,cs[i%4],i%4===1||i%4===3?'#94a3b8':cs[i%4])}${t(43+i*51,132,i+1,M,12)}`).join('')}${t(220,165,`第${n}張是${ns[p]}`,p===2?R:p===0?B:C,20)}`);};h.querySelector('#ps').oninput=draw;draw();},caption:'教材先從週期排列開始，再進入數形規律。',example:eg('藍、白、紅、白重複排列，第21張是什麼顏色？',['每4張一組。','21÷4＝5餘1，看下一組第1張。'],'藍色。')},
    {sec:'3-1',secName:'圖形和數形的規律',title:'先比較相鄰圖形，找出每次增加的部分',points:['觀察不變和新增加的部分。','把每一圖的數量依序記錄。','相鄰兩圖的差能提示規律。'],formula:{label:'數量變化',tex:'3,5,7,9,\\ldots'},visual:h=>h.innerHTML=svg('0 0 440 220',`${[1,2,3,4].map((n,i)=>`${b(35+i*100,70,70,35+n*12,'#ecfdf5',C)}${t(70+i*100,55,`圖${n}`,C,15)}${t(70+i*100,180,`${2*n+1}根`,B,15)}`).join('')}`),caption:'每多排一個三角形，就多用2枝吸管。',example:eg('數列3、5、7、9的下一個數？',['相鄰兩數都增加2。','9再加2。'],'11。')},
    {sec:'3-1',secName:'圖形和數形的規律',title:'把圖形編號和數量排成表，對應關係更清楚',points:['第一列寫圖形編號。','第二列寫物件數量。','橫著看增加量，直著看對應。'],formula:{label:'對應表',tex:'\\text{第1圖}\\to3,\\quad\\text{第2圖}\\to5'},visual:h=>h.innerHTML=cards(['三角形個數：1　2　3　4','吸管數量：3　5　7　9','每增加1個三角形，多2枝吸管']),caption:'表格把圖形規律轉成數量關係。',example:eg('第5圖需要幾枝吸管？',['數量依序3、5、7、9。','再增加2。'],'11枝。')},
    {sec:'3-1',secName:'圖形和數形的規律',title:'用「圖形數×2＋1」預測任一圖的吸管數',points:['每個三角形貢獻2枝。','再加最左邊固定的1枝。','代入不同圖號都要成立。'],formula:{label:'文字算式',tex:'\\text{吸管數}=\\text{圖形數}\\times2+1'},visual:h=>{h.innerHTML='<div><div id="fig"></div><div class="ictrl"><label>第 <span class="ival" id="nv">4</span> 圖</label><input id="ns" type="range" min="1" max="10" value="4"></div></div>';const draw=()=>{const n=+h.querySelector('#ns').value;h.querySelector('#nv').textContent=n;h.querySelector('#fig').innerHTML=cards([`圖形數：${n}`,`${n}×2＋1`,`吸管數：${2*n+1}枝`]);};h.querySelector('#ns').oninput=draw;draw();},caption:'拖動圖形編號，算式與結果同步更新。',example:eg('第10圖需要幾枝吸管？',['10×2＋1。','20＋1。'],'21枝。')},
    {sec:'3-2',secName:'和差積商不變',title:'白晝和黑夜合起來都是一天，和固定為24小時',points:['白晝變長時，黑夜會變短。','兩個時間量相加仍是24小時。','先寫文字關係，再代入已知量。'],formula:{label:'和不變',tex:'\\text{白晝}+\\text{黑夜}=24'},visual:h=>{h.innerHTML='<div><div id="fig"></div><div class="ictrl"><label>白晝 <span class="ival" id="dv">12</span> 小時</label><input id="ds" type="range" min="8" max="16" step="0.5" value="12"></div></div>';const draw=()=>{const d=+h.querySelector('#ds').value,n=24-d;h.querySelector('#dv').textContent=d;h.querySelector('#fig').innerHTML=svg('0 0 440 175',`${b(35,45,370*d/24,62,'#fef3c7',A)}${b(35+370*d/24,45,370*n/24,62,'#dbeafe',B)}${t(220,142,`${d}＋${n}＝24`,C,22)}`);};h.querySelector('#ds').oninput=draw;draw();},caption:'白晝與黑夜互相增減，但一天仍是24小時。',example:eg('某天白晝14又1/4小時，黑夜有多久？',['白晝＋黑夜＝24。','24－14又1/4。'],'9又3/4小時。')},
    {sec:'3-2',secName:'和差積商不變',title:'兩人的年齡同時增加，年齡差保持不變',points:['先求現在相差幾歲。','過相同年數，兩人增加相同歲數。','年齡差不會隨年份改變。'],formula:{label:'差不變',tex:'35-7=(35+10)-(7+10)=28'},visual:h=>{h.innerHTML='<div><div id="fig"></div><div class="ictrl"><label><span class="ival" id="yv">0</span> 年後</label><input id="ys" type="range" min="0" max="20" step="5" value="0"></div></div>';const draw=()=>{const y=+h.querySelector('#ys').value;h.querySelector('#yv').textContent=y;h.querySelector('#fig').innerHTML=cards([`媽媽：${35+y}歲`,`孩子：${7+y}歲`,`${35+y}－${7+y}＝28歲`]);};h.querySelector('#ys').oninput=draw;draw();},caption:'年齡一起增加，兩人的差仍然相同。',example:eg('媽媽35歲、孩子7歲，10年後相差幾歲？',['現在相差35－7＝28。','兩人都加10，差不變。'],'28歲。')},
    {sec:'3-2',secName:'和差積商不變',title:'每包重量乘包數，始終等於白米總重量',points:['全部白米分裝完，總重量不變。','每包越重，裝成的包數越少。','用每包重量×包數核對。'],formula:{label:'積不變',tex:'\\text{每包重量}\\times\\text{包數}=60'},visual:h=>{h.innerHTML='<div><div id="fig"></div><div class="ictrl"><label>分裝方式 <span class="ival" id="wv">每包2公斤</span></label><input id="ws" type="range" min="0" max="2" value="0"></div></div>';const ways=[[2,30],[4,15],[5,12]],draw=()=>{const [w,n]=ways[+h.querySelector('#ws').value];h.querySelector('#wv').textContent=`每包${w}公斤`;h.querySelector('#fig').innerHTML=cards([`每包重量：${w}公斤`,`裝成包數：${n}包`,`${w}×${n}＝60公斤`]);};h.querySelector('#ws').oninput=draw;draw();},caption:'改變分裝方式，白米總重量仍是60公斤。',example:eg('60公斤白米，每包4公斤，可裝幾包？',['每包重量×包數＝60。','60÷4。'],'15包。')},
    {sec:'3-2',secName:'和差積商不變',title:'總價除以數量，始終等於一個物品的價錢',points:['購買的是相同單價的物品。','總價和數量同倍變化，單價不變。','用總價÷數量求一個的價錢。'],formula:{label:'商不變',tex:'\\text{總價}\\div\\text{數量}=15'},visual:h=>{h.innerHTML='<div><div id="fig"></div><div class="ictrl"><label>購買紀錄 <span class="ival" id="cv">6個</span></label><input id="cs" type="range" min="0" max="2" value="0"></div></div>';const cases=[[90,6],[180,12],[300,20]],draw=()=>{const [m,n]=cases[+h.querySelector('#cs').value];h.querySelector('#cv').textContent=`${n}個`;h.querySelector('#fig').innerHTML=cards([`總價：${m}元`,`購買數量：${n}個`,`${m}÷${n}＝15元`]);};h.querySelector('#cs').oninput=draw;draw();},caption:'總價與數量改變，杯子蛋糕的單價仍是15元。',example:eg('同款蛋糕6個共90元，每個多少元？',['總價÷購買數量。','90÷6。'],'15元。')},
    {sec:'3-3',secName:'間隔問題',title:'兩個編號之間的距離，先算相差幾個間隔',points:['相鄰兩點之間才是一個間隔。','間隔數＝大編號－小編號。','距離＝間隔數×每個間距。'],formula:{label:'編號距離',tex:'(51-36)\\times25=375'},visual:h=>h.innerHTML=cards(['第36號到第51號','間隔數：51－36＝15','距離：15×25＝375公尺']),caption:'點的個數通常比間隔數多1。',example:eg('第36號到第51號路燈，每隔25公尺，相距多少？',['間隔數＝51－36＝15。','15×25。'],'375公尺。')},
    {sec:'3-3',secName:'間隔問題',title:'直線頭尾都有物件，物件數比間隔數多1',points:['全長÷間距求間隔數。','頭尾都有，物件數＝間隔數＋1。','畫端點可避免忘記加1。'],formula:{label:'頭尾都有',tex:'\\text{物件數}=\\text{全長}\\div\\text{間距}+1'},visual:h=>h.innerHTML=cards(['全長100公尺，每隔20公尺','間隔數：100÷20＝5','路燈數：5＋1＝6']),caption:'五個間隔需要六個端點。',example:eg('100公尺道路頭尾都設燈，每隔20公尺，共幾盞？',['100÷20＝5個間隔。','頭尾都有，再加1。'],'6盞。')},
    {sec:'3-3',secName:'間隔問題',title:'直線端點情況決定物件數要加1、不變或減1',points:['頭尾都有：間隔數＋1。','只有一端：物件數等於間隔數。','兩端都沒有：間隔數－1。'],formula:{label:'三種端點',tex:'5+1=6,\\quad5,\\quad5-1=4'},visual:h=>{h.innerHTML='<div><div id="fig"></div><div class="ictrl"><label>端點 <span class="ival" id="mv">頭尾都有</span></label><input id="ms" type="range" min="0" max="2" value="0"></div></div>';const labels=['頭尾都有','只有一端','兩端都沒有'],nums=[6,5,4],draw=()=>{const m=+h.querySelector('#ms').value;h.querySelector('#mv').textContent=labels[m];h.querySelector('#fig').innerHTML=cards(['固定有5個間隔',labels[m],`物件數：${nums[m]}個`]);};h.querySelector('#ms').oninput=draw;draw();},caption:'拖動端點情況，直接比較三種答案。',example:eg('100公尺道路兩端都不設燈，每隔20公尺，共幾盞？',['有5個間隔。','兩端都沒有，5－1。'],'4盞。')},
    {sec:'3-3',secName:'間隔問題',title:'封閉路徑首尾相接，物件數等於間隔數',points:['封閉路徑沒有多出來的端點。','物件數＝全長÷間距。','求間距時，用全長÷物件數。'],formula:{label:'封閉路徑',tex:'\\text{物件數}=\\text{全長}\\div\\text{間距}'},visual:h=>h.innerHTML=svg('0 0 440 220',`<circle cx="220" cy="110" r="75" fill="#ecfdf5" stroke="${C}" stroke-width="4"/>${Array.from({length:8},(_,i)=>{const q=i*Math.PI/4;return `<circle cx="${220+75*Math.cos(q)}" cy="${110+75*Math.sin(q)}" r="7" fill="${A}"/>`;}).join('')}${t(220,115,'8個間隔',C,20)}${t(220,205,'首尾相接：8個物件',B,17)}`),caption:'繞一圈回到起點，不需再多算一個端點。',example:eg('周長80公尺的圓形步道，每10公尺設燈，共幾盞？',['80÷10＝8個間隔。','封閉路徑物件數等於間隔數。'],'8盞。')}
  ];
  window.DECK.push({ch:3,title:'數量關係',color:C,sections:['3-1 圖形和數形的規律','3-2 和差積商不變','3-3 間隔問題'],slides});
})();
